package gui.others;

import controllers.category.ICategoryController;
import controllers.city.ICityController;
import gui.others.getCategories.GetCategoriesPanel;
import gui.others.getCities.GetCitiesPanel;
import gui.others.createCategory.CreateCategoryPanel;
import gui.others.createCity.CreateCityPanel;
import gui.user.registerAirline.RegisterAirlinePanel;

import javax.swing.*;
import javax.swing.border.EtchedBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class OtherPanel extends JPanel {

    private ICategoryController categoryController;
    private ICityController cityController;

    private JPanel createCategoryPanel;
    private JPanel createCityPanel;
    private JPanel getCategoriesPanel;
    private JPanel getCitiesPanel;
    
    private JPanel contentPanel;

    public OtherPanel(ICategoryController categoryController, ICityController cityController) {
        this.categoryController = categoryController;
        this.cityController = cityController;

        initComponents(); // Generated by JFormDesigner
        initPanels(); // Inicializa los paneles
        initListeners(); // Inicializa los listeners

        // Remueve el panel de evalaución del JFormDesigner
        try { setBorder(new EtchedBorder(EtchedBorder.LOWERED)); } catch ( Exception ignored ) {}
    }

    private void initPanels() {
        createCategoryPanel = new CreateCategoryPanel(categoryController);
        createCityPanel = new CreateCityPanel(cityController);
        getCategoriesPanel = new GetCategoriesPanel(categoryController);
        getCitiesPanel = new GetCitiesPanel(cityController);
    }

    private void initListeners() {
        createCategoryBtn.addMouseListener(createListener(createCategoryPanel));
        createCityBtn.addMouseListener(createListener(createCityPanel));
        getCatgoriesBtn.addMouseListener(createListener(getCategoriesPanel));
        getCitiesBtn.addMouseListener(createListener(getCitiesPanel));
    }

    // Permite crear los listeners para los botones.
    private MouseAdapter createListener(JPanel panel) {
        return new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Remover solo si ya existe un contentPanel
                if (contentPanel != null) {
                    // Verificar si el contentPanel ya es del mismo tipo que el nuevo panel
                    if (contentPanel.getClass().equals(panel.getClass())) {
                        return;
                    }
                    remove(contentPanel);
                }

                System.out.println(panel.getClass().getSimpleName() + " button clicked");
                // Crear el nuevo contentPanel con el contenido del panel proporcionado
                contentPanel = panel;
                add(contentPanel);
                revalidate();
                repaint();
            }
        };

    }

    // JFormDesigner - Variables declaration - DO NOT MODIFY  //GEN-BEGIN:variables  @formatter:off
    // Generated using JFormDesigner Evaluation license - dotto
    private JPanel NavPanel;
    private JButton createCityBtn;
    private JButton createCategoryBtn;
    private JButton getCitiesBtn;
    private JButton getCatgoriesBtn;
    // JFormDesigner - End of variables declaration  //GEN-END:variables  @formatter:on

    private void initComponents() {
        // JFormDesigner - Component initialization - DO NOT MODIFY  //GEN-BEGIN:initComponents  @formatter:off
        // Generated using JFormDesigner Evaluation license - dotto
        NavPanel = new JPanel();
        createCityBtn = new JButton();
        createCategoryBtn = new JButton();
        getCitiesBtn = new JButton();
        getCatgoriesBtn = new JButton();

        //======== this ========
        setPreferredSize(new Dimension(640, 600));
        setMinimumSize(new Dimension(640, 600));
        setMaximumSize(new Dimension(640, 600));
        setBackground(new Color(0xeeeeee));
        setBorder (new javax. swing. border. CompoundBorder( new javax .swing .border .TitledBorder (new javax. swing. border. EmptyBorder
        ( 0, 0, 0, 0) , "JF\u006frm\u0044es\u0069gn\u0065r \u0045va\u006cua\u0074io\u006e", javax. swing. border. TitledBorder. CENTER, javax. swing. border
        . TitledBorder. BOTTOM, new java .awt .Font ("D\u0069al\u006fg" ,java .awt .Font .BOLD ,12 ), java. awt
        . Color. red) , getBorder( )) );  addPropertyChangeListener (new java. beans. PropertyChangeListener( ){ @Override public void
        propertyChange (java .beans .PropertyChangeEvent e) {if ("\u0062or\u0064er" .equals (e .getPropertyName () )) throw new RuntimeException( )
        ; }} );
        setLayout(new BorderLayout());

        //======== NavPanel ========
        {
            NavPanel.setMinimumSize(new Dimension(640, 60));
            NavPanel.setPreferredSize(new Dimension(640, 60));
            NavPanel.setMaximumSize(new Dimension(640, 60));
            NavPanel.setBackground(new Color(0x386aac));
            NavPanel.setBorder(new EtchedBorder());
            NavPanel.setLayout(new GridLayout());

            //---- createCityBtn ----
            createCityBtn.setText("+ Registrar Ciudad");
            NavPanel.add(createCityBtn);

            //---- createCategoryBtn ----
            createCategoryBtn.setText("+ Crear Categoria");
            NavPanel.add(createCategoryBtn);

            //---- getCitiesBtn ----
            getCitiesBtn.setText("\ud83d\udcc4 Listar Ciudades");
            NavPanel.add(getCitiesBtn);

            //---- getCatgoriesBtn ----
            getCatgoriesBtn.setText("\ud83d\udcc4 Listar Categorias");
            NavPanel.add(getCatgoriesBtn);
        }
        add(NavPanel, BorderLayout.NORTH);
        // JFormDesigner - End of component initialization  //GEN-END:initComponents  @formatter:on
    }
}

