package gui.others;

import controllers.airport.IAirportController;
import controllers.category.ICategoryController;
import controllers.city.ICityController;
import gui.others.createAirport.CreateAirportPanel;
import gui.others.getAirports.GetAirportsPanel;
import gui.others.getCategories.GetCategoriesPanel;
import gui.others.getCities.GetCitiesPanel;
import gui.others.createCategory.CreateCategoryPanel;
import gui.others.createCity.CreateCityPanel;
import gui.user.registerAirline.RegisterAirlinePanel;

import javax.swing.*;
import javax.swing.border.EtchedBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class OtherPanel extends JPanel {

    private ICategoryController categoryController;
    private ICityController cityController;
    private IAirportController airportController;

    private JPanel createCategoryPanel;
    private JPanel createCityPanel;
    private JPanel createAirportPanel;
    private JPanel getCategoriesPanel;
    private JPanel getCitiesPanel;
    private JPanel getAirportsPanel;
    
    private JPanel contentPanel;

    public OtherPanel(
            ICategoryController categoryController,
            ICityController cityController,
            IAirportController airportController
    ) {
        this.categoryController = categoryController;
        this.cityController = cityController;
        this.airportController = airportController;

        initComponents(); // Generated by JFormDesigner
        initPanels(); // Inicializa los paneles
        initListeners(); // Inicializa los listeners

        // Remueve el panel de evalaución del JFormDesigner
        try { setBorder(new EtchedBorder(EtchedBorder.LOWERED)); } catch ( Exception ignored ) {}
    }

    private void initPanels() {
        createCategoryPanel = new CreateCategoryPanel(categoryController);
        createCityPanel = new CreateCityPanel(cityController);
        createAirportPanel = new CreateAirportPanel(airportController, cityController);
        getCategoriesPanel = new GetCategoriesPanel(categoryController);
        getCitiesPanel = new GetCitiesPanel(cityController);
        getAirportsPanel = new GetAirportsPanel(airportController);
    }

    private void initListeners() {
        createCategoryBtn.addMouseListener(createListener(createCategoryPanel));
        createCityBtn.addMouseListener(createListener(createCityPanel));
        createAirportBtn.addMouseListener(createListener(createAirportPanel));
        getCatgoriesBtn.addMouseListener(createListener(getCategoriesPanel));
        getCitiesBtn.addMouseListener(createListener(getCitiesPanel));
        getAirportsBtn.addMouseListener(createListener(getAirportsPanel));
    }

    // Permite crear los listeners para los botones.
    private MouseAdapter createListener(JPanel panel) {
        return new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Remover solo si ya existe un contentPanel
                if (contentPanel != null) {
                    // Verificar si el contentPanel ya es del mismo tipo que el nuevo panel
                    if (contentPanel.getClass().equals(panel.getClass())) {
                        return;
                    }
                    remove(contentPanel);
                }

                System.out.println(panel.getClass().getSimpleName() + " button clicked");
                // Crear el nuevo contentPanel con el contenido del panel proporcionado
                contentPanel = panel;
                add(contentPanel);
                revalidate();
                repaint();
            }
        };

    }

    // JFormDesigner - Variables declaration - DO NOT MODIFY  //GEN-BEGIN:variables  @formatter:off
    // Generated using JFormDesigner Evaluation license - asd
    private JPanel NavPanel;
    private JButton createCityBtn;
    private JButton createCategoryBtn;
    private JButton createAirportBtn;
    private JButton getCitiesBtn;
    private JButton getCatgoriesBtn;
    private JButton getAirportsBtn;
    // JFormDesigner - End of variables declaration  //GEN-END:variables  @formatter:on

    private void initComponents() {
        // JFormDesigner - Component initialization - DO NOT MODIFY  //GEN-BEGIN:initComponents  @formatter:off
        // Generated using JFormDesigner Evaluation license - asd
        NavPanel = new JPanel();
        createCityBtn = new JButton();
        createCategoryBtn = new JButton();
        createAirportBtn = new JButton();
        getCitiesBtn = new JButton();
        getCatgoriesBtn = new JButton();
        getAirportsBtn = new JButton();

        //======== this ========
        setPreferredSize(new Dimension(640, 600));
        setMinimumSize(new Dimension(640, 600));
        setMaximumSize(new Dimension(640, 600));
        setBackground(new Color(0xeeeeee));
        setBorder (new javax. swing. border. CompoundBorder( new javax .swing .border .TitledBorder (new
        javax. swing. border. EmptyBorder( 0, 0, 0, 0) , "JF\u006frmD\u0065sig\u006eer \u0045val\u0075ati\u006fn", javax
        . swing. border. TitledBorder. CENTER, javax. swing. border. TitledBorder. BOTTOM, new java
        .awt .Font ("Dia\u006cog" ,java .awt .Font .BOLD ,12 ), java. awt
        . Color. red) , getBorder( )) );  addPropertyChangeListener (new java. beans.
        PropertyChangeListener( ){ @Override public void propertyChange (java .beans .PropertyChangeEvent e) {if ("\u0062ord\u0065r" .
        equals (e .getPropertyName () )) throw new RuntimeException( ); }} );
        setLayout(new BorderLayout());

        //======== NavPanel ========
        {
            NavPanel.setMinimumSize(new Dimension(640, 70));
            NavPanel.setPreferredSize(new Dimension(640, 70));
            NavPanel.setMaximumSize(new Dimension(640, 70));
            NavPanel.setBackground(new Color(0x386aac));
            NavPanel.setBorder(new EtchedBorder());
            NavPanel.setLayout(new GridBagLayout());
            ((GridBagLayout)NavPanel.getLayout()).columnWidths = new int[] {0, 0, 0, 0};
            ((GridBagLayout)NavPanel.getLayout()).rowHeights = new int[] {34, 32, 0};
            ((GridBagLayout)NavPanel.getLayout()).columnWeights = new double[] {1.0, 1.0, 1.0, 1.0E-4};
            ((GridBagLayout)NavPanel.getLayout()).rowWeights = new double[] {1.0, 0.0, 1.0E-4};

            //---- createCityBtn ----
            createCityBtn.setText("+ Registrar Ciudad");
            createCityBtn.setMaximumSize(new Dimension(41646542, 34));
            NavPanel.add(createCityBtn, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.BOTH,
                new Insets(0, 0, 0, 0), 0, 0));

            //---- createCategoryBtn ----
            createCategoryBtn.setText("+ Crear Categoria");
            createCategoryBtn.setMaximumSize(new Dimension(41646542, 34));
            createCategoryBtn.setMinimumSize(new Dimension(150, 34));
            createCategoryBtn.setPreferredSize(new Dimension(150, 34));
            NavPanel.add(createCategoryBtn, new GridBagConstraints(1, 0, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.BOTH,
                new Insets(0, 0, 0, 0), 0, 0));

            //---- createAirportBtn ----
            createAirportBtn.setText("+ Registrar Aeropuerto");
            createAirportBtn.setMaximumSize(new Dimension(41646542, 34));
            createAirportBtn.setMinimumSize(new Dimension(150, 34));
            createAirportBtn.setPreferredSize(new Dimension(150, 34));
            NavPanel.add(createAirportBtn, new GridBagConstraints(2, 0, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.BOTH,
                new Insets(0, 0, 0, 0), 0, 0));

            //---- getCitiesBtn ----
            getCitiesBtn.setText("\ud83d\udcc4 Listar Ciudades");
            getCitiesBtn.setMaximumSize(new Dimension(41646542, 34));
            getCitiesBtn.setMinimumSize(new Dimension(150, 34));
            getCitiesBtn.setPreferredSize(new Dimension(150, 34));
            NavPanel.add(getCitiesBtn, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.BOTH,
                new Insets(0, 0, 0, 0), 0, 0));

            //---- getCatgoriesBtn ----
            getCatgoriesBtn.setText("\ud83d\udcc4 Listar Categorias");
            getCatgoriesBtn.setMaximumSize(new Dimension(41646542, 34));
            getCatgoriesBtn.setMinimumSize(new Dimension(150, 34));
            getCatgoriesBtn.setPreferredSize(new Dimension(150, 34));
            NavPanel.add(getCatgoriesBtn, new GridBagConstraints(1, 1, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.BOTH,
                new Insets(0, 0, 0, 0), 0, 0));

            //---- getAirportsBtn ----
            getAirportsBtn.setText("\ud83d\udcc4 Listar Aeropuertos");
            getAirportsBtn.setMaximumSize(new Dimension(41646542, 34));
            getAirportsBtn.setMinimumSize(new Dimension(150, 34));
            getAirportsBtn.setPreferredSize(new Dimension(150, 34));
            NavPanel.add(getAirportsBtn, new GridBagConstraints(2, 1, 1, 1, 0.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.BOTH,
                new Insets(0, 0, 0, 0), 0, 0));
        }
        add(NavPanel, BorderLayout.NORTH);
        // JFormDesigner - End of component initialization  //GEN-END:initComponents  @formatter:on
    }
}

