name: compile-and-upload.yaml

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  JAR_NAME: VolandoUY-1.0-SNAPSHOT.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Compile JAR
        run: |
          cd VolandoUY && mvn clean package -Dmaven.test.skip=true

      - name: Publish the new JAR
        run: |
          mkdir -p release
          rm -f release/*.jar
          mv VolandoUY/target/$JAR_NAME release/$JAR_NAME
          
      - name: Create commit, push to new branch, and open PR
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'action@github.com'
      
          # Create and switch to new branch
          BRANCH_NAME="new_release_$(date +%Y%m%d_%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b "$BRANCH_NAME"
      
          # Stage and commit files
          ls -l release
          git add -f release/$JAR_NAME
          git commit -m "[AUTO] New JAR release"

          git show --stat
          git status
      
          # Push to new branch and set upstream
          git push --set-upstream origin "$BRANCH_NAME"
          
