name: Compile and Upload the JAR

on:
  push:
    branches: [main]

permissions:
  content: write
    
env:
  JAR_NAME: VolandoUY-1.0-SNAPSHOT.jar

jobs:
  auto_release:
    if: "!contains(github.event.head_commit.message, '[AUTO] New JAR release')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Compile JAR
        run: |
          cd VolandoUY && mvn clean package -Dmaven.test.skip=true

      - name: Publish the new JAR
        run: |
          mkdir -p release
          rm -f release/*.jar
          mv VolandoUY/target/$JAR_NAME release/$JAR_NAME

      - name: Create commit, push to new branch, and open PR
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'action@github.com'
      
          # Create and switch to new branch
          BRANCH_NAME="auto/new_release_$(date +%Y%m%d_%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b "$BRANCH_NAME"
      
          # Stage and commit files
          git add -f release/$JAR_NAME
          git commit -m "chore: add the new release"
      
          # Push to new branch and set upstream
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Create PR via API
        id: create_pr
        run: |
          # Create PR and capture output (prints something like: "https://github.com/org/repo/pull/123")
          OUTPUT=$(gh pr create \
            --title "[AUTO] New JAR release" \
            --body "This PR was automatically generated." \
            --base main \
            --head "$BRANCH_NAME")

          echo "PR output: $OUTPUT"

          # Extract URL (last word in output)
          PR_URL=$(echo "$OUTPUT" | grep -Eo 'https://github.com[^ ]+')
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.APP_CENTRAL_PAT }}

      - name: Merge PR automatically
        run: |
          gh pr merge "$PR_URL" --merge --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ secrets.APP_CENTRAL_PAT }}
